@startuml filled-player
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 150
skinparam nodesep 50

$empty_grid_3x1()
$join_grid_3x1("hidden")
@enduml

@startuml player-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 1

<style>
  .axis {
    FontColor: black;
    FontSize: 30;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)
@enduml

@startuml matrix-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 40
skinparam nodesep 1

<style>
  label {
    FontSize: 30;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)

$fill_matrix(2)
$join_matrix_3x3()
@enduml

@startuml player-protocol-component
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 60
skinparam nodesep 20
skinparam NoteTextAlignment left
scale max 1200 width

$fill_players()
$fill_protocol()
$fill_environ()

player ~d~ protocol
protocol ~d~ environ
@enduml

@startuml aspects-with-protocols
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 40

<style>
  .matrix {
    FontSize: 30;
    FontColor: Grey;
  }
</style>

$iconify_players(1)

$fill_grid_3x3(2)

$empty_axes()
$join_axes_3x3()

$fill_matrix(2)
$join_matrix_3x3()
@enduml

@startuml protocols-with-components
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 40

$fill_players(1)

$fill_grid_5x5("run", 2)

$empty_axes()
$join_axes_5x5()
@enduml
