@startuml filled-player
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 150
skinparam nodesep 50

$empty_grid_3x1()
$join_grid_3x1("hidden")
@enduml

@startuml player-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 1

<style>
  .axis {
    FontColor: black;
    FontSize: 30;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)
@enduml

@startuml matrix-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 40
skinparam nodesep 1

<style>
  label {
    FontSize: 30;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)

$fill_matrix(2)
$join_matrix_3x3()
@enduml

@startuml player-protocol-component
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 60
skinparam nodesep 20
skinparam NoteTextAlignment left
scale max 1200 width

$fill_players()
$fill_protocol()
$fill_component()

player ~d~ protocol
protocol ~d~ component
@enduml

@startuml system-position-participant
!include lib/game.puml!core
!include lib/i18n.puml!ru

$fill_players()
$fill_environ()

rectangle " " as system {
  portin "$translate(topmid, 1)" as p1
  portin "$translate(botmid, 1)" as p2
  portin "$translate(leftmid, 1)" as p3
  portin "$translate(rightmid, 1)" as p4
  portout "$translate(topmid, 1)" as po1
  portout "$translate(botmid, 1)" as po2
  portout "$translate(leftmid, 1)" as po3
  portout "$translate(rightmid, 1)" as po4
  
  $fill_leftcomp()
  $fill_rightcomp()
  $fill_topcomp()
  $fill_botcomp()
}

player ~~ p1
player ~~ p2
player ~~ p3
player ~~ p4
p1 ~~ topcomp
p2 ~~ botcomp
p3 ~~ leftcomp
p4 ~~ rightcomp
topcomp ~~ po1
botcomp ~~ po2
leftcomp ~~ po3
rightcomp ~~ po4
po1 ~~ environ
po2 ~~ environ
po3 ~~ environ
po4 ~~ environ
@enduml

@startuml aspects-with-protocols
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 40

<style>
  .matrix {
    FontSize: 30;
    FontColor: Grey;
  }
</style>

$iconify_players(1)

$fill_grid_3x3(2)

$empty_axes()
$join_axes_3x3()

$fill_matrix(2)
$join_matrix_3x3()
@enduml

@startuml protocols-with-components
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 20
skinparam nodesep 40

$fill_players(1)

$fill_grid_5x5("run", 2)

$empty_axes()
$join_axes_5x5()
@enduml
