@startuml filled-player
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 150
skinparam nodesep 50

$empty_grid_3x1()
$join_grid_3x1("hidden")
@enduml

@startuml filled-mentor-and-filled-engine
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 30
skinparam nodesep 50

$fill_character_agent("run")
$empty_grid_3x1()
$fill_avatar_agent("run")
$join_grid_5x1("hidden")
@enduml

@startuml outlined-character-and-outlined-avatar
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 30
skinparam nodesep 50

$fill_character_agent("run")
$draft_protocol(leftmid)
$fill_players()
$draft_protocol(rightmid)
$fill_avatar_agent("run")
$join_grid_5x1("hidden")
@enduml

@startuml mentor-player-relationship
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 20
skinparam NoteTextAlignment left
scale max 1200 width

$fill_character_agent("run")
$fill_characters(N)
$fill_players()

leftcomp ~[hidden]d~ leftmid
leftmid ~[hidden]d~ player

note as N1
# $translate(mentor_character_management, N)
# $translate(player_character_control, N)
end note

note as N2
# $translate(player_character_management, N)
# $translate(mentor_character_prediction, N)
end note

N1 -d- leftcomp
player -d- N2
@enduml

@startuml player-engine-relationship
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 20
skinparam NoteTextAlignment left
scale max 1200 width

$fill_players()
$fill_avatars(N)
$fill_avatar_agent("run")

player ~[hidden]d~ rightmid
rightmid ~[hidden]d~ rightcomp

note as N1
# $translate(player_avatar_management, N)
# $translate(engine_avatar_prediction, N)
end note

note as N2
# $translate(engine_avatar_management, N)
# $translate(player_avatar_control, N)
end note

N1 -d- player
rightcomp -d- N2
@enduml

@startuml filled-characters-and-filled-avatars
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 25
skinparam nodesep 50

$fill_players(2)
$fill_grid_5x1("run", 2)
$join_grid_5x1("hidden")
@enduml

@startmindmap axis-x-with-clarifications-en
!include lib/game.puml!core
!include lib/i18n.puml!ru

<style>
node {
  MaximumWidth 800
  Padding 5
  Margin 10
}
.term {
  FontSize 30
  LineColor DimGrey
  LineThickness 0.5
  BackgroundColor transparent
}
.defn {
  FontSize 20
  LineThickness 0.5
  BackgroundColor transparent
}
</style>

+ уровни\nабстракции <<term>>
' ++_ **2** <<defn>>
' +++ $translate(intention, N), $translate(action, N), $translate(event, N), $translate(effect, N) <<defn>>
++_ **1** <<defn>>
+++ $translate(leftmid, N), $translate(rightmid, N), $translate(botmid, N), $translate(topmid, N) <<defn>>
++_ **0** <<defn>>
+++ $translate(topleft, N), $translate(botleft, N), $translate(topright, N), $translate(botright, N) <<defn>>
++_ **1** <<defn>>
+++ участники, правила, права <<defn>>

+ права\nдоступа <<term>>
++ владение <<defn>>
+++_ создание или уничтожение <<defn>>
++ распоряжение <<defn>>
+++_ произвольное изменение <<defn>>
++ применение <<defn>>
+++_ использование по назначению <<defn>>
++ потребление <<defn>>
+++_ чтение, слушание, просмотр <<defn>>

+ порядок\nдоступа <<term>>
++ инициатива <<defn>>
+++_ действие без одобрения, поощрение или порицание <<defn>>
++ эскалация <<defn>>
+++_ запрос, рассмотрение, одобрение или отказ <<defn>>
++ консенсус <<defn>>
+++_ предложение, переговоры, одобрение или отказ <<defn>>

+ уровни\nсубъектности <<term>>
++ дизайнер <<defn>>
+++_ полные права над сущностями 0 уровня <<defn>>
++ наставник <<defn>>
+++_ полные права над сущностями 1 уровня <<defn>>
+++_ применение сущностей любого уровня <<defn>>
+++_ потребление сущностей любого уровня <<defn>>
++ игрок <<defn>>
+++_ распоряжение сущностями 1 уровня <<defn>>
+++_ применение сущностей любого уровня <<defn>>
+++_ потребление сущностей любого уровня <<defn>>
++ оператор <<defn>>
+++_ применение сущностей любого уровня <<defn>>
+++_ потребление сущностей любого уровня <<defn>>
++ наблюдатель <<defn>>
+++_ потребление сущностей любого уровня <<defn>>
@endmindmap