@startuml (id=core)
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/cog>
!include <tupadr3/font-awesome-5/pen_square>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/user_alt>
!include <tupadr3/font-awesome-5/user_cog>
!include <tupadr3/font-awesome-5/user_edit>
!include <tupadr3/font-awesome-5/question>
!include <tupadr3/font-awesome-5/question_circle>
!include <tupadr3/font-awesome-5/puzzle_piece>
!include <tupadr3/font-awesome-5/fan>
!include <tupadr3/font-awesome-5/film>
!include <tupadr3/font-awesome-5/book>
!include <tupadr3/font-awesome-5/book_open>
!include <tupadr3/font-awesome-5/book_reader>
!include <tupadr3/font-awesome-5/layer_group>
!include <tupadr3/font-awesome-5/microchip>
!include <tupadr3/font-awesome/gamepad>
!include <tupadr3/font-awesome-5/heartbeat>
!include <tupadr3/font-awesome/history>
!include <tupadr3/font-awesome-5/mask>
!include <tupadr3/font-awesome-5/robot>
!include <tupadr3/font-awesome-5/pencil_ruler>
!include <tupadr3/font-awesome-5/file_alt>
!include <tupadr3/font-awesome-5/file_code>
!include <tupadr3/font-awesome-5/file_contract>
!include <tupadr3/font-awesome-5/file_image>
!include <tupadr3/material/extension>
!include <tupadr3/material/description>
!include <tupadr3/material/local_library>
!include <tupadr3/material/toys>
!include <tupadr3/material/description>
!include <tupadr3/material/videogame_asset>

!include i18n.puml!core

skinparam defaultTextAlignment center
' skinparam defaultFontName Ubuntu Mono
skinparam defaultFontName Nimbus Mono PS
skinparam defaultFontSize 15
scale max 800 width
' skinparam dpi 150

left to right direction

<style>
  rectangle {
    FontSize: 20;
  }
  collections {
    FontSize: 20;
  }
  card {
    FontSize: 20;
  }
  label {
    FontSize: 20;
  }
  .axis {
    FontSize: 20;
    FontName: Nimbus Mono PS;
    FontColor: DimGrey;
  }
  .plane {
    FontSize: 16;
  }
  .sth {
  }
  .nth {
    FontColor: Transparent;
  }
  .puzzler {
    FontSize: 40;
    FontStyle: bold;
  }
</style>

!procedure $empty_player()
  label player [
  ]
!endprocedure

!procedure $iconify_players($count=1)
  !if ($count==1)
    label player [
      <$user_alt{scale=0.9}>
    ]
  !else
    label player [
      <$user_alt{scale=0.45}>
      <$user_alt{scale=0.45}> <$user_alt{scale=0.45}>
    ]
  !endif
!endprocedure

!procedure $fill_players($count=1)
  !if ($count==1)
    label player [
      <$user_alt{scale=0.9}>
      $translate(player, $count)
    ]
  !else
    label player [
      <$user_alt{scale=0.45}>
      <$user_alt{scale=0.45}> <$user_alt{scale=0.45}>
      $translate(player, $count)
    ]
  !endif
!endprocedure

!procedure $empty_character_agent()
  label leftcomp [
  ]
!endprocedure

!procedure $iconify_character_agent()
  label leftcomp [
    ' <$user_edit{scale=0.9}>
    <$user_alt>
  ]
!endprocedure

!procedure $fill_leftcomp($time="dev")
  label leftcomp <<agent>> [
    ' <$user_alt{scale=0.9}>
    <$robot{scale=1.0}>
    ' <$user_cog{scale=0.9}>
    ' <$user_edit{scale=0.9}>
  !if ($time=="dev")
    $translate(characterWriter)
  !elseif ($time=="run")
    $translate(predictorComp)
  !else
    !assert %false() : "Unknown time"
  !endif
  ]
!endprocedure

!procedure $empty_avatar_agent()
  label rightcomp [
  ]
!endprocedure

!procedure $iconify_avatar_agent()
  label rightcomp [
    ' <$user_cog{scale=0.9}>
    <$user_alt>
  ]
!endprocedure

!procedure $fill_rightcomp($time="dev")
  label rightcomp <<agent>> [
    ' <$user_alt{scale=0.9}>
    <$robot{scale=1.0}>
    ' <$user_cog{scale=0.9}>
    ' <$user_edit{scale=0.9}>
  !if ($time=="dev")
    $translate(avatarDesigner)
  !elseif ($time=="run")
    $translate(narratorComp)
  !else
    !assert %false() : "Unknown time"
  !endif
  ]
!endprocedure

!procedure $empty_character()
  label leftmid [
  ]
!endprocedure

!procedure $fill_leftmid($count=1)
  !if ($count==1)
    rectangle leftmid [
      ' <$extension{scale=0.52}><size:7> </size>$translate(leftmid, $count)
      <$layer_group{scale=0.52}><size:7> </size>$translate(leftmid, $count)
    ]
  !else
    collections leftmid [
      ' <$extension{scale=0.52}><size:7> </size>$translate(leftmid, $count)
      <$layer_group{scale=0.52}><size:7> </size>$translate(leftmid, $count)
    ]
  !endif
!endprocedure

!procedure $textify_characters($count=1)
  !if ($count==1)
    card leftmid #back:transparent;line.dotted [
      $translate(character2, $count)
    ]
  !else
    collections leftmid #back:transparent;line.dotted [
      $translate(character2, $count)
    ]
  !endif
!endprocedure

!procedure $empty_avatar()
  label rightmid [
  ]
!endprocedure

!procedure $fill_rightmid($count=1)
  !if ($count==1)
    rectangle rightmid [
      ' <U+0000><$book_open{scale=0.50}><size:7> </size>$translate(rightmid, $count)<U+0000>
      <U+0000><$layer_group{scale=0.50}><size:7> </size>$translate(rightmid, $count)<U+0000>
    ]
  !else
    collections rightmid [
      ' <U+0000><$book_open{scale=0.50}><size:7> </size>$translate(rightmid, $count)<U+0000>
      <U+0000><$layer_group{scale=0.50}><size:7> </size>$translate(rightmid, $count)<U+0000>
    ]
  !endif
!endprocedure

!procedure $textify_avatars($count=1)
  !if ($count==1)
    card "  $translate(avatar2, $count)  " as rightmid #back:transparent;line.dotted
  !else
    collections " $translate(avatar2, $count) " as rightmid #back:transparent;line.dotted
  !endif
!endprocedure

!procedure $fill_topcomp($time="run")
  label topcomp <<agent>> [
    ' <$user_alt{scale=0.9}>
    <$robot{scale=1.0}>
    ' <$user_cog{scale=0.9}>
    ' <$user_edit{scale=0.9}>
  !if ($time=="dev")
    $translate(storyWriter)
  !elseif ($time=="run")
    $translate(mentorComp)
  !else
    !assert %false() : "Unknown time"
  !endif
  ]
!endprocedure

!procedure $fill_botcomp($time="run")
  label botcomp <<agent>> [
    ' <$user_alt{scale=0.9}>
    <$robot{scale=1.0}>
    ' <$user_cog{scale=0.9}>
    ' <$user_edit{scale=0.9}>
  !if ($time=="dev")
    $translate(narrativeDesigner)
  !elseif ($time=="run")
    $translate(engineComp)
  !else
    !assert %false() : "Unknown time"
  !endif
  ]
!endprocedure

!procedure $fill_botmid($count=1)
  !if ($count==1)
    rectangle botmid [
      ' <$pen_square{scale=0.52}><size:7> </size>$translate(botmid, $count)
      <$layer_group{scale=0.52}><size:7> </size>$translate(botmid, $count)
    ]
  !else
    collections botmid [
      ' <$pen_square{scale=0.52}><size:7> </size>$translate(botmid, $count)
      <$layer_group{scale=0.52}><size:7> </size>$translate(botmid, $count)
    ]
  !endif
!endprocedure

!procedure $fill_topmid($count=1)
  !if ($count==1)
    rectangle topmid [
      ' <U+0000><$cog{scale=0.52}><size:7> </size>$translate(topmid, $count)<U+0000>
      <U+0000><$layer_group{scale=0.52}><size:7> </size>$translate(topmid, $count)<U+0000>
    ]
  !else
    collections topmid [
      ' <U+0000><$cog{scale=0.52}><size:7> </size>$translate(topmid, $count)<U+0000>
      <U+0000><$layer_group{scale=0.52}><size:7> </size>$translate(topmid, $count)<U+0000>
    ]
  !endif
!endprocedure

!procedure $draft_protocol($id)
  rectangle $id #line.dashed;back:transparent [
    <U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>
  ]
!endprocedure

!procedure $fill_axes()
  $fill_axis_x()
  $fill_axis_y()
!endprocedure

!procedure $fill_axis_x($style=axis)
  label leftmid <<$style>> [
    $translate(xAxisNegativeLabel)
  ]
  label rightmid <<$style>> [
    $translate(xAxisPositiveLabel)
  ]
!endprocedure

!procedure $fill_axis_y($style=axis)
  label topmid <<$style>> [
    $translate(yAxisPositiveLabel)
  ]
  label botmid <<$style>> [
    $translate(yAxisNegativeLabel)
  ]
!endprocedure

!procedure $empty_axes()
  $empty_axis_x()
  $empty_axis_y()
!endprocedure

!procedure $empty_axis_x()
  label leftmost <<axis>> [
  ]
  label rightmost <<axis>> [
  ]
!endprocedure

!procedure $empty_axis_y()
  label topmost <<axis>> [
  ]
  label botmost <<axis>> [
  ]
!endprocedure

!procedure $empty_axes_3x3()
  $empty_axis_x()
  $empty_axis_y()
  $empty_character()
  $empty_avatar()
  label botmid [
  ]
  label topmid [
  ]
!endprocedure

!procedure $join_axis_x($mode="thickness=1")
  leftmost ~[$mode]d~ player
  player ~[$mode]d~ rightmost
!endprocedure

!procedure $join_axis_y($mode="thickness=1")
  topmost ~[$mode]r~ player
  player ~[$mode]r~ botmost
!endprocedure

!procedure $join_axes_1x1($x="thickness=1", $y="thickness=1")
  $join_axis_x($x)
  $join_axis_y($y)
!endprocedure

!procedure $join_axes_3x1($mode="thickness=1")
  leftmost ~[$mode]d~ leftmid
  $join_grid_3x1($mode)
  rightmid ~[$mode]d~ rightmost
!endprocedure

!procedure $join_axes_1x3($mode="thickness=1")
  topmost ~[$mode]r~ topmid
  $join_grid_1x3($mode)
  botmid ~[$mode]r~ botmost
!endprocedure

!procedure $join_axes_3x3($x="thickness=1", $y="thickness=1")
  $join_axes_3x1($x)
  $join_axes_1x3($y)
!endprocedure

!procedure $join_axes_5x1($x="thickness=1", $y="thickness=1")
  ' leftmost ~[$x]d~ leftcomp
  $join_grid_5x1($x)
  ' rightcomp ~[$x]d~ rightmost
!endprocedure

!procedure $join_axes_1x5($x="thickness=1", $y="thickness=1")
  ' topmost ~[$x]r~ topcomp
  $join_grid_1x5($x)
  ' botcomp ~[$x]r~ botmost
!endprocedure

!procedure $join_axes_5x3($x="thickness=1", $y="thickness=1")
  $join_axes_5x1($x)
  $join_axes_1x3($y)
!endprocedure

!procedure $join_axes_5x5($x="thickness=1", $y="thickness=1")
  $join_axes_5x1($x)
  $join_axes_1x5($y)
!endprocedure

!procedure $fill_arcs($count=1)
  label "  $translate(botleft, $count)  " as botleft <<matrix>>
!endprocedure

!procedure $fill_themes($count=1)
  label "  $translate(topleft, $count)  " as topleft <<matrix>>
!endprocedure

!procedure $fill_mechanics($count=1)
  label "$translate(botright, $count)" as botright <<matrix>>
!endprocedure

!procedure $fill_settings($count=1)
  label "$translate(topright, $count)" as topright <<matrix>>
!endprocedure

!procedure $fill_matrix($count=2)
  $fill_arcs($count)
  $fill_themes($count)
  $fill_settings($count)
  $fill_mechanics($count)
!endprocedure

!procedure $join_matrix_3x1()
  botleft -[hidden]r- leftmid
  leftmid -[hidden]r- topleft
  botright -[hidden]r- rightmid
  rightmid -[hidden]r- topright
!endprocedure

!procedure $join_matrix_3x3()
  botleft -[hidden]d- botmid
  botmid -[hidden]d- botright
  topleft -[hidden]d- topmid
  topmid -[hidden]d- topright
!endprocedure

!procedure $empty_grid_1x3()
  label botmid [
  ]
  $fill_players()
  label topmid [
  ]
!endprocedure

!procedure $empty_grid_3x1()
  $empty_character()
  $fill_players()
  $empty_avatar()
!endprocedure

!procedure $empty_grid_3x3()
  $empty_character()
  $empty_avatar()

  label botmid [
  ]
  label topmid [
  ]
!endprocedure

!procedure $fill_grid_3x1($count=1)
  $fill_leftmid($count)
  $fill_rightmid($count)
!endprocedure

!procedure $fill_grid_1x3($count=1)
  $fill_botmid($count)
  $fill_topmid($count)
!endprocedure

!procedure $fill_grid_3x3($count=1)
  $fill_grid_3x1($count)
  $fill_grid_1x3($count)
!endprocedure

!procedure $fill_grid_5x1($time="dev", $count=1)
  $fill_leftcomp($time)
  $fill_grid_3x1($count)
  $fill_rightcomp($time)
!endprocedure

!procedure $fill_grid_5x3($time="dev", $count=1)
  $fill_grid_5x1($time, $count)
  $fill_grid_1x3($count)
!endprocedure

!procedure $fill_grid_5x5($time="dev", $count=1)
  $fill_leftcomp($time)
  $fill_rightcomp($time)
  $fill_grid_3x1($count)
  $fill_grid_1x3($count)
  $fill_topcomp($time)
  $fill_botcomp($time)
!endprocedure

!procedure $join_grid_1x3($mode="thickness=1")
  topmid ~[$mode]r~ player
  player ~[$mode]r~ botmid
!endprocedure

!procedure $join_grid_3x1($mode="thickness=1")
  leftmid ~[$mode]d~ player
  player ~[$mode]d~ rightmid
!endprocedure

!procedure $join_grid_3x3($mode="thickness=1")
  $join_grid_3x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!procedure $join_grid_5x1($mode="thickness=1")
  leftcomp ~[$mode]d~ leftmid
  $join_grid_3x1($mode)
  rightmid ~[$mode]d~ rightcomp
!endprocedure

!procedure $join_half_5x1($mode="thickness=1")
  leftcomp ~[$mode]d~ leftmid
  leftmid ~[$mode]d~ player
!endprocedure

!procedure $join_grid_1x5($mode="thickness=1")
  topcomp ~[$mode]r~ topmid
  $join_grid_1x3($mode)
  botmid ~[$mode]r~ botcomp
!endprocedure

!procedure $join_grid_5x3($mode="thickness=1")
  $join_grid_5x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!procedure $join_grid_5x5($mode="thickness=1")
  $join_grid_5x1($mode)
  $join_grid_1x5($mode)
!endprocedure

!$debug = %false()
!if ($debug)

!endif
@enduml
