@startuml (id=core)
!function $translate($key, $count=1)
  !if ($count==1)
    !return $locale[$key].one
  !else
    !return $locale[$key].many
  !endif
!endfunction
@enduml

@startuml (id=ru)
!$locale = {
  "layer": {
    "one": "слой"
  },
  "abstraction": {
    "one": "абстракция",
    "many": "абстракции"
  },
  "player": {
    "one": "игрок",
    "many": "игроки"
  },
  "characterWriter": {
    "one": "сценарист"
  },
  "predictorComp": {
    "one": "оракул"
  },
  "avatarDesigner": {
    "one": "дизайнер"
  },
  "narratorComp": {
    "one": "нарратор"
  },
  "storyWriter": {
    "one": "сценарист"
  },
  "mentorComp": {
    "one": "ментор"
  },
  "protocol": {
    "one": "протокол"
  },
  "environ": {
    "one": "среда"
  },
  "narrativeDesigner": {
    "one": "дизайнер"
  },
  "engineComp": {
    "one": "движок"
  },
  "xAxisNegativeTerm": {
    ' "one": "абстрактное"
    ' "one": "абстракция"
    ' "one": "логическое"
    "one": "декларация"
  },
  "xAxisPositiveTerm": {
    ' "one": "физическое"
    ' "one": "реализация"
    ' "one": "реальное"
    ' "one": "осязаемое"
    ' "one": "материальное"
    ' "one": "конкретное"
    "one": "детализация"
  },
  "yAxisNegativeTerm": {
    "one": "процесс"
  },
  "yAxisPositiveTerm": {
    "one": "состояние"
    ' "one": "структура"
  },
  "xAxisNegativeLabel": {
    ' "one": "а б с т р а к ц и я"
    ' "one": "п о л а г а е м о е"
    ' "one": "г и п о т е т и ч е с к о е"
    "one": "в о з м о ж н о с т ь"
    ' "one": "а б с т р а к т н о е"
    ' "one": "а б с т р а к т н о с т ь"
    ' "one": "с п е ц и ф и к а ц и я"
  },
  "xAxisPositiveLabel": {
    ' "one": "к о н к р е ц и я"
    ' "one": "к о н к р е т н о е"
    ' "one": "т р а к т у е м о е"
    ' "one": "ф а к т и ч е с к о е"
    "one": "д а н н о с т ь"
    ' "one": "к о н к р е т н о с т ь"
    ' "one": "р е а л и з а ц и я"
    ' "one": "и м п л е м е н т а ц и я"
  },
  "yAxisNegativeLabel": {
    ' "one": "п\nо\nв\nе\nд\nе\nн\nи\nе"
    "one": "к\nо\nн\nк\nр\nе\nт\nн\nо\nе"
    ' "one": "в\nо\nп\nл\nо\nщ\nе\nн\nи\nе"
  },
  "yAxisPositiveLabel": {
    ' "one": "и\nд\nе\nя"
    ' "one": "с\nо\nс\nт\nо\nя\nн\nи\nе"
    "one": "а\nб\nс\nт\nр\nа\nк\nт\nн\nо\nе"
  },
  "declaration": {
    "one": "объявление"
  },
  "translation": {
    "one": "трансляция"
  },
  "realization": {
    "one": "реализация"
  },
  "specification": {
    "one": "спецификация"
  },
  "detalization": {
    "one": "детализация"
  },
  "definition": {
    "one": "определение"
  },
  "entailment": {
    "one": "следствие"
  },
  "consequence": {
    "one": "следствие"
  },
  "structure": {
    "one": "структура"
  },
  "algorithm": {
    "one": "алгоритм"
  },
  "plot": {
    "one": "сюжет",
    "many": "сюжеты"
  },
  "topmid": {
    "one": "персонаж",
    "many": "персонажи"
  },
  "botmid": {
    "one": "аватар",
    "many": "аватары"
  },
  "leftmid": {
    "one": "видение",
    "many": "видения"
  },
  "rightmid": {
    "one": "нарратив",
    "many": "нарративы"
  },
  "topleft": {
    "one": "арка",
    "many": "арки"
  },
  "botleft": {
    "one": "механика",
    "many": "механики"
  },
  "topright": {
    "one": "тема",
    "many": "тема"
  },
  "botright": {
    "one": "сеттинг",
    "many": "сеттинг"
  },
  "idea": {
    ' "one": "идея"
    "one": "лор"
  },
  "model": {
    "one": "модель"
  },
  "prediction": {
    "one": "объяснение"
  },
  "grammar": {
    "one": "грамматика"
  },
  "query": {
    ' "one": "запрос"
    ' "one": "обращение"
    "one": "сообщение"
  },
  "meaning": {
    ' "one": "значение"
    "one": "семантика"
    ' "one": "смысл"
  },
  "intention": {
    ' "one": "цель"
    ' "one": "образ"
    ' "one": "мечта"
    ' "one": "амбиция"
    "one": "намерение",
    "many": "намерения"
    ' "one": "стремление"
  },
  "cause": {
    ' "one": "основание"
    ' "one": "причина"
    ' "one": "оказия"
    "one": "повод"
    ' "one": "мотив"
  },
  "concern": {
    ' "one": "обоснование"
    "one": "уместность"
    ' "one": "приемлемость"
    ' "one": "допустимость"
    ' "one": "релевантность"
    ' "one": "адекватность"
  },
  "world": {
    "one": "мир"
  },
  "observation": {
    "one": "наблюдение"
  },
  "interface": {
    "one": "интерфейс"
  },
  "command": {
    "one": "команда"
  },
  "effect": {
    "one": "эффект",
    "many": "эффекты"
  },
  "action": {
    "one": "действие",
    "many": "действия"
  },
  "event": {
    "one": "событие",
    "many": "события"
  },
  "resource": {
    "one": "ресурс"
  },
  "inertia": {
    ' "one": "доступ"
    ' "one": "право"
    ' "one": "привилегия"
    "one": "разрешение"
    ' "one": "консенсус"
  },
  "logic": {
    "one": "логика"
  },
  "judgment": {
    ' "one": "суждение"
    ' "one": "знание"
    ' "one": "исследование"
    ' "one": "изучение"
    "one": "познание"
    ' "one": "информация"
  },
  "rationality": {
    "one": "рациональность"
  },
  "rule": {
    ' "one": "правило"
    "one": "инструкция"
  },
  "alienation": {
    ' "one": "обособление"
    "one": "отчуждение"
  },
  "authenticity": {
    ' "one": "подлинность"
    "one": "объективность"
  },
  "cyclicality": {
    "one": "цикличность"
    ' "one": "ритмичность"
  },
  "typicality": {
    "one": "типичность"
    ' "one": "схожесть"
  },
  "isolation": {
    ' "one": "независимость"
    "one": "изолированность"
  },
  "intuition": {
    "one": "интуиция"
  },
  "feeling": {
    "one": "ощущение"
  },
  "emotionality": {
    "one": "эмоциональность"
  },
  "inspiration": {
    "one": "вдохновение"
  },
  "participation": {
    ' "one": "вовлечение"
    "one": "сопричастие"
  },
  "subjectivity": {
    "one": "субъективность"
  },
  "finiteness": {
    "one": "конечность"
  },
  "uniqueness": {
    "one": "уникальность"
  },
  "interactivity": {
    "one": "интерактивность"
  },
  "mentor_character_management": {
    "many": "управление персонажами наставника"
  },
  "mentor_character_prediction": {
    "many": "предсказание персонажей наставника"
  },
  "player_character_control": {
    "many": "контроль персонажей игрока"
  },
  "player_character_management": {
    "many": "управление персонажами игрока"
  },
  "player_avatar_management": {
    "many": "управление аватарами игрока"
  },
  "player_avatar_control": {
    "many": "контроль аватаров игрока"
  },
  "engine_avatar_prediction": {
    "many": "предсказание аватаров движка"
  },
  "engine_avatar_management": {
    "many": "управление аватарами движка"
  }
}
@enduml

@startuml (id=en)
!$locale = {
  "layer": {
    "one": "layer"
  },
  "abstraction": {
    "one": "abstraction",
    "many": "abstractions"
  },
  "event": {
    "one": "event",
    "many": "events"
  },
  "effect": {
    "one": "effect",
    "many": "effects"
  },
  "player": {
    "one": "player",
    "many": "players"
  },
  "characterWriter": {
    "one": "writer"
    ' "one": "game\nwriter"
  },
  "predictorComp": {
    ' "one": "controller"
    "one": "oracle"
    ' "one": "game\nmentor"
  },
  "avatarDesigner": {
    "one": "designer"
    ' "one": "game\ndesigner"
  },
  "narratorComp": {
    ' "one": "controller"
    "one": "narrator"
    ' "one": "game\nengine"
  },
  "storyWriter": {
    "one": "writer"
    ' "one": "game\nwriter"
  },
  "mentorComp": {
    ' "one": "teller"
    "one": "mentor"
    ' "one": "game\nengine"
  },
  "narrativeDesigner": {
    "one": "designer"
    ' "one": "game\ndesigner"
  },
  "engineComp": {
    ' "one": "performer"
    "one": "engine"
    ' "one": "game\nmentor"
  },
  "character2": {
    "one": "c h a r a c t e r",
    "many": "c h a r a c t e r s"
  },
  "avatar2": {
    "one": "a v a t a r",
    "many": "a v a t a r s"
  },
  "devtime": {
    "one": "devtime"
  },
  "runtime": {
    "one": "runtime"
  },
  "xAxisNegativeTerm": {
    "one": "abstract"
    ' "one": "declaration"
  },
  "xAxisPositiveTerm": {
    "one": "concrete"
    ' "one": "detalization"
  },
  "yAxisNegativeTerm": {
    "one": "hypothetical"
  },
  "yAxisPositiveTerm": {
    "one": "factual"
  },
  "xAxisNegativeLabel": {
    ' "one": "l o g i c a l"
    ' "one": "m e n t a l"
    ' "one": "a b s t r a c t"
    ' "one": "p r o j e c t i v e"
    "one": "h y p o t h e t i c a l"
    ' "one": "a b s t r a c t i o n"
    ' "one": "a b s t r a c t n e s s"
    ' "one": "d e c l a r a t i o n"
  },
  "xAxisPositiveLabel": {
    ' "one": "p h y s i c a l"
    ' "one": "m a t e r i a l"
    ' "one": "c o n c r e t e"
    ' "one": "i n t e r p r e t i v e"
    "one": "f a c t u a l"
    ' "one": "c o n c r e t i o n"
    ' "one": "c o n c r e t e n e s s"
    ' "one": "s p e c i f i c a t i o n"
    ' "one": "i m p l e m e n t a t i o n"
    ' "one": "r    e    a    l"
    ' "one": "d e t a l i z a t i o n"
  },
  "yAxisNegativeLabel": {
    "one": "c\no\nn\nc\nr\ne\nt\ne"
    ' "one": "b\ne\nh\na\nv\ni\no\nr"
    ' "one": "i\nn\nt\ne\nr\np\nr\ne\nt\ni\nv\ne"
  },
  "yAxisPositiveLabel": {
    "one": "a\nb\ns\nt\nr\na\nc\nt"
    ' "one": "s\nt\na\nt\ne"
    ' "one": "s\n\nt\n\na\n\nt\n\ne"
    ' "one": "s\nt\nr\nu\nc\nt\nu\nr\ne"
    ' "one": "p\nr\no\nj\ne\nc\nt\ni\nv\ne"
  },
  "abstract": {
    "one": "abstract"
  },
  "concrete": {
    "one": "concrete"
  },
  "declaration": {
    "one": "declaration"
  },
  "translation": {
    "one": "translation"
  },
  "realization": {
    "one": "realization"
  },
  "specification": {
    "one": "specification"
  },
  "detalization": {
    "one": "detalization"
  },
  "definition": {
    "one": "definition"
  },
  "structure": {
    "one": "structure"
  },
  "entailment": {
    "one": "entailment"
  },
  "consequence": {
    "one": "consequence"
  },
  "algorithm": {
    "one": "algorithm"
  },
  "plot": {
    "one": "plot",
    "many": "plots"
  },
  "topmid": {
    "one": "character",
    "many": "characters"
  },
  "botmid": {
    "one": "avatar",
    "many": "avatars"
  },
  "leftmid": {
    "one": "foresight",
    "many": "predictions"
  },
  "rightmid": {
    "one": "narrative",
    "many": "narratives"
  },
  "topleft": {
    "one": "arc",
    "many": "arcs"
  },
  "botleft": {
    "one": "mechanic",
    "many": "mechanics"
  },
  "topright": {
    "one": "theme",
    "many": "theme"
  },
  "botright": {
    "one": "setting",
    "many": "setting"
  },
  "idea": {
    ' "one": "idea"
    "one": "lore"
  },
  "model": {
    "one": "model"
  },
  "prediction": {
    "one": "prediction"
  },
  "grammar": {
    "one": "grammar"
  },
  "query": {
    ' "one": "query"
    ' "one": "record"
    ' "one": "statement"
    "one": "message"
  },
  "meaning": {
    "one": "meaning"
    ' "one": "semantic"
  },
  "intention": {
    ' "one": "vision"
    "one": "intention"
  },
  "cause": {
    ' "one": "cause"
    "one": "reason"
    ' "one": "occasion"
    ' "one": "motive"
  },
  "concern": {
    "one": "relevance"
    ' "one": "knowledge"
  },
  "world": {
    "one": "world"
  },
  "observation": {
    "one": "observation"
  },
  "interface": {
    "one": "interface"
  },
  "command": {
    "one": "command"
  },
  "effect": {
    "one": "effect"
  },
  "action": {
    "one": "action"
  },
  "resource": {
    "one": "resource"
  },
  "inertia": {
    "one": "permission"
    ' "one": "access"
    ' "one": "right"
  },
  "logic": {
    "one": "logic"
  },
  "judgment": {
    "one": "knowledge"
    ' "one": "cognition"
  },
  "resource": {
    "one": "resource"
  },
  "rationality": {
    "one": "rationality"
  },
  "rule": {
    ' "one": "rule"
    "one": "instruction"
  },
  "alienation": {
    ' "one": "estrangement"
    "one": "alienation"
  },
  "authenticity": {
    "one": "objectivity"
  },
  "cyclicality": {
    ' "one": "cyclicality"
    "one": "rhythmicity"
  },
  "typicality": {
    "one": "similarity"
    ' "one": "typicality"
  },
  "isolation": {
    "one": "isolation"
  },
  "intuition": {
    "one": "intuition"
  },
  "feeling": {
    "one": "feeling"
  },
  "emotionality": {
    "one": "emotionality"
  },
  "inspiration": {
    "one": "inspiration"
  },
  "participation": {
    "one": "participation"
  },
  "subjectivity": {
    "one": "subjectivity"
  },
  "finiteness": {
    "one": "finiteness"
  },
  "uniqueness": {
    "one": "uniqueness"
  },
  "interactivity": {
    "one": "interactivity"
  },
  "mentor_character_management": {
    "many": "mentor characters management"
  },
  "mentor_character_prediction": {
    "many": "mentor characters prediction"
  },
  "player_character_management": {
    "many": "player characters management"
  },
  "player_character_control": {
    "many": "player characters control"
  },
  "player_avatar_management": {
    "many": "player avatars management"
  },
  "player_avatar_control": {
    "many": "player avatars control"
  },
  "engine_avatar_management": {
    "many": "engine avatars management"
  },
  "engine_avatar_prediction": {
    "many": "engine avatars prediction"
  }
}
@enduml